[build]
base="findmywager/"
publish="findmywager/build"
command="npm build"

[[redirects]]
from="/"
to ="/index.html"
status=200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"